// front2/app/(auth)/login.tsx
import { Link, useRouter } from "expo-router";
import { useState } from "react";
import {
  KeyboardAvoidingView,
  Platform,
  ScrollView,
  Text,
  View,
} from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { toast } from "sonner-native";

import { authApi } from "@/api/auth";
import { extractErrorMessage } from "@/api/error";
import { Brand } from "@/components/Brand";
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";
import { useAuthStore } from "@/stores/auth";

export default function Login() {
  const router = useRouter();
  const setAuth = useAuthStore((s) => s.set);

  const [email, setEmail] = useState("");
  const [senha, setSenha] = useState("");
  const [carregando, setCarregando] = useState(false);
  const [erro, setErro] = useState<string | null>(null);

  const enviar = async () => {
    if (carregando) return;
    setCarregando(true);
    setErro(null);
    try {
      const res = await authApi.login(email.trim(), senha);
      await setAuth(res.token, {
        id: res.usuarioId,
        nome: res.nome,
        email: res.email,
      });
      toast.success(`Bem-vindo de volta, ${res.nome.split(" ")[0]}.`);
      router.replace("/captura");
    } catch (err) {
      setErro(extractErrorMessage(err, "Não consegui entrar. Confere os dados."));
    } finally {
      setCarregando(false);
    }
  };

  const valido = email.trim() !== "" && senha !== "";

  return (
    <SafeAreaView className="flex-1 bg-bg" edges={["top", "bottom"]}>
      <KeyboardAvoidingView
        behavior={Platform.OS === "ios" ? "padding" : undefined}
        className="flex-1"
      >
        <ScrollView
          contentContainerStyle={{
            flexGrow: 1,
            justifyContent: "center",
            paddingHorizontal: 24,
            gap: 32,
          }}
          keyboardShouldPersistTaps="handled"
        >
          <View className="items-center gap-3">
            <Brand size={36} />
            <Text className="text-text-dim text-center leading-relaxed max-w-[320px]">
              Bem-vindo de volta. Entra com suas credenciais que eu cuido do
              resto.
            </Text>
          </View>

          <View className="gap-3.5">
            <Input
              label="Email"
              value={email}
              onChangeText={setEmail}
              placeholder="voce@exemplo.com"
              keyboardType="email-address"
              autoCapitalize="none"
              autoComplete="email"
              autoCorrect={false}
              testID="login-email"
            />

            <Input
              label="Senha"
              value={senha}
              onChangeText={setSenha}
              placeholder="••••••••"
              secureTextEntry
              autoComplete="current-password"
              testID="login-senha"
            />

            {erro && (
              <Text className="text-danger text-xs" testID="login-erro">
                {erro}
              </Text>
            )}

            <Button
              label={carregando ? "Entrando..." : "Entrar"}
              onPress={enviar}
              disabled={!valido}
              loading={carregando}
              testID="login-submit"
            />
          </View>

          <View className="flex-row items-center gap-3">
            <View className="flex-1 h-px bg-border" />
            <Text className="text-text-subtle text-xs">ou</Text>
            <View className="flex-1 h-px bg-border" />
          </View>

          <View className="flex-row justify-center gap-1.5">
            <Text className="text-text-dim text-[13px]">Primeira vez?</Text>
            <Link href="/cadastro" className="text-text font-medium text-[13px]">
              Criar conta
            </Link>
          </View>
        </ScrollView>
      </KeyboardAvoidingView>

      <View className="absolute bottom-6 left-0 right-0 items-center">
        <Text className="text-text-subtle text-[11px] tracking-wider">
          JARVIS • v0.1 BETA
        </Text>
      </View>
    </SafeAreaView>
  );
}

// front/src/app/features/auth/login.component.ts
import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { AuthService } from '../../core/auth/auth.service';
import { BrandLogoComponent } from '../../shared/brand-logo.component';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [FormsModule, RouterLink, BrandLogoComponent],
  template: `
    <main
      class="min-h-screen grid place-items-center px-6 py-12 bg-bg bg-accent-glow"
      data-testid="login-page"
    >
      <div class="w-full max-w-[380px] flex flex-col gap-8">
        <app-brand-logo />

        <p class="text-center text-text-dim leading-relaxed -mt-3" data-testid="jarvis-greeting">
          Bem-vindo de volta. Entra com suas credenciais que eu cuido do resto.
        </p>

        <form
          class="flex flex-col gap-3.5"
          data-testid="login-form"
          (ngSubmit)="enviar()"
          #f="ngForm"
        >
          <div class="flex flex-col gap-1.5">
            <label class="field-label" for="email">Email</label>
            <input
              id="email"
              name="email"
              type="email"
              class="input-base"
              placeholder="voce@exemplo.com"
              autocomplete="email"
              data-testid="login-email-input"
              [(ngModel)]="email"
              required
            />
          </div>

          <div class="flex flex-col gap-1.5">
            <label class="field-label" for="senha">Senha</label>
            <input
              id="senha"
              name="senha"
              type="password"
              class="input-base"
              placeholder="••••••••"
              autocomplete="current-password"
              data-testid="login-password-input"
              [(ngModel)]="senha"
              required
            />
          </div>

          @if (erro()) {
            <p class="text-danger text-xs" data-testid="login-erro">{{ erro() }}</p>
          }

          <button
            type="submit"
            class="btn-primary mt-1"
            data-testid="login-submit-btn"
            [disabled]="carregando() || f.invalid"
          >
            {{ carregando() ? 'Entrando...' : 'Entrar' }}
          </button>
        </form>

        <div class="flex items-center gap-3 text-text-subtle text-xs">
          <span class="flex-1 h-px bg-border"></span>
          ou
          <span class="flex-1 h-px bg-border"></span>
        </div>

        <p class="text-center text-[13px] text-text-dim">
          Primeira vez por aqui?
          <a
            routerLink="/cadastro"
            class="text-text font-medium border-b border-border-strong hover:border-accent pb-px"
            data-testid="login-signup-link"
            >Criar conta</a
          >
        </p>
      </div>

      <div
        class="fixed bottom-6 left-1/2 -translate-x-1/2 text-text-subtle text-[11px] tracking-wider"
      >
        JARVIS • v0.1 BETA
      </div>
    </main>
  `,
})
export class LoginComponent {
  private readonly auth = inject(AuthService);
  private readonly router = inject(Router);

  email = '';
  senha = '';
  carregando = signal(false);
  erro = signal<string | null>(null);

  enviar(): void {
    if (this.carregando()) return;
    this.carregando.set(true);
    this.erro.set(null);

    this.auth.login(this.email, this.senha).subscribe({
      next: () => {
        this.carregando.set(false);
        this.router.navigateByUrl('/captura');
      },
      error: (err) => {
        this.carregando.set(false);
        this.erro.set(err?.error?.mensagem ?? 'Não consegui entrar. Confere os dados.');
      },
    });
  }
}
