// frontNovo/components/TarefaForm.tsx
"use client";

import { useEffect, useState } from "react";
import { toast } from "sonner";

import { extractErrorMessage } from "@/lib/api/error";
import { Prioridade, type Tarefa } from "@/lib/api/types";
import { useCategorias } from "@/lib/hooks/useCategorias";
import { usePrazos } from "@/lib/hooks/usePrazos";
import {
  useAtualizarTarefa,
  useCriarTarefa,
} from "@/lib/hooks/useTarefas";
import { cn } from "@/lib/utils";

import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

interface TarefaFormProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  tarefa?: Tarefa | null;
  nomeInicial?: string;
}

const PRIORIDADES = [
  { value: Prioridade.Urgente, label: "Urgente" },
  { value: Prioridade.Importante, label: "Importante" },
  { value: Prioridade.Normal, label: "Normal" },
  { value: Prioridade.Baixa, label: "Baixa" },
] as const;

export function TarefaForm({
  open,
  onOpenChange,
  tarefa,
  nomeInicial = "",
}: TarefaFormProps) {
  const { data: categorias = [] } = useCategorias();
  const { data: prazos = [] } = usePrazos();
  const criar = useCriarTarefa();
  const atualizar = useAtualizarTarefa();

  const [nome, setNome] = useState("");
  const [prioridade, setPrioridade] = useState<number>(Prioridade.Normal);
  const [categoriaIds, setCategoriaIds] = useState<string[]>([]);
  const [prazoId, setPrazoId] = useState<string | null>(null);
  const [dataCustom, setDataCustom] = useState<string>("");
  const [horario, setHorario] = useState<string>("23:59");
  const [usandoCustom, setUsandoCustom] = useState(false);
  const [erro, setErro] = useState<string | null>(null);

  const editando = !!tarefa;
  const salvando = criar.isPending || atualizar.isPending;

  useEffect(() => {
    if (!open) return;
    if (tarefa) {
      setNome(tarefa.nome);
      setPrioridade(tarefa.prioridade);
      setCategoriaIds(tarefa.categorias.map((c) => c.id));
      setPrazoId(tarefa.prazoId);
      if (tarefa.dataPrazo && !tarefa.prazoId) {
        setUsandoCustom(true);
        setDataCustom(tarefa.dataPrazo.substring(0, 10));
      } else {
        setUsandoCustom(false);
        setDataCustom("");
      }
      if (tarefa.horarioFinal) {
        setHorario(tarefa.horarioFinal.substring(0, 5));
      }
    } else {
      setNome(nomeInicial);
      setPrioridade(Prioridade.Normal);
      setCategoriaIds([]);
      setPrazoId(null);
      setDataCustom("");
      setHorario("23:59");
      setUsandoCustom(false);
    }
    setErro(null);
  }, [open, tarefa, nomeInicial]);

  const toggleCategoria = (id: string) => {
    setCategoriaIds((prev) =>
      prev.includes(id) ? prev.filter((c) => c !== id) : [...prev, id],
    );
  };

  const enviar = () => {
    if (!nome.trim()) {
      setErro("Coloca um nome pra tarefa.");
      return;
    }

    let dataPrazoCustom: string | null = null;
    let horarioFinal: string | null = null;
    if (usandoCustom) {
      if (!dataCustom) {
        setErro("Informa a data ou escolhe outro prazo.");
        return;
      }
      dataPrazoCustom = new Date(dataCustom + "T00:00:00").toISOString();
      if (horario) {
        const [h, m] = horario.split(":");
        horarioFinal = `${h.padStart(2, "0")}:${m.padStart(2, "0")}:00`;
      }
    }

    const payload = {
      nome: nome.trim(),
      prioridade: prioridade as 1 | 2 | 3 | 4,
      categoriaIds,
      prazoId: usandoCustom ? null : prazoId,
      dataPrazoCustom,
      horarioFinal,
    };

    const opts = {
      onSuccess: (msg: string) => {
        toast.success(msg);
        onOpenChange(false);
      },
      onError: (err: unknown) => {
        setErro(
          extractErrorMessage(err, "Não consegui salvar. Tenta de novo."),
        );
      },
    };

    if (editando && tarefa) {
      atualizar.mutate(
        { id: tarefa.id, payload },
        {
          onSuccess: () => opts.onSuccess("Tarefa atualizada."),
          onError: opts.onError,
        },
      );
    } else {
      criar.mutate(payload, {
        onSuccess: () => opts.onSuccess("Anotado."),
        onError: opts.onError,
      });
    }
  };

  return (
    <Dialog open={open} onOpenChange={(v) => !salvando && onOpenChange(v)}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>{editando ? "Editar tarefa" : "Nova tarefa"}</DialogTitle>
        </DialogHeader>

        <div className="px-5 py-4 flex flex-col gap-4 overflow-y-auto">
          <div className="flex flex-col gap-1.5">
            <Label htmlFor="nome">Nome</Label>
            <Input
              id="nome"
              value={nome}
              onChange={(e) => setNome(e.target.value)}
              placeholder="O que precisa ser feito"
              maxLength={200}
              autoFocus
            />
          </div>

          <div className="flex flex-col gap-1.5">
            <Label>Categorias</Label>
            {categorias.length === 0 ? (
              <p className="text-xs text-text-subtle">
                Nenhuma categoria cadastrada. Crie em Configurações.
              </p>
            ) : (
              <div className="flex flex-wrap gap-1.5">
                {categorias.map((cat) => {
                  const ativa = categoriaIds.includes(cat.id);
                  return (
                    <button
                      key={cat.id}
                      type="button"
                      onClick={() => toggleCategoria(cat.id)}
                      className={cn(
                        "px-2.5 py-1 rounded text-[13px] border transition-colors",
                        ativa
                          ? "bg-accent/15 border-accent/40 text-text"
                          : "bg-bg-input border-border-strong text-text-dim hover:text-text",
                      )}
                    >
                      {cat.nome}
                    </button>
                  );
                })}
              </div>
            )}
          </div>

          <div className="flex flex-col gap-1.5">
            <Label>Prioridade</Label>
            <div className="grid grid-cols-4 gap-1.5">
              {PRIORIDADES.map((p) => {
                const ativa = prioridade === p.value;
                return (
                  <button
                    key={p.value}
                    type="button"
                    onClick={() => setPrioridade(p.value)}
                    className={cn(
                      "px-2 py-2 rounded text-[12px] border transition-colors",
                      ativa
                        ? "bg-accent/15 border-accent/40 text-text"
                        : "bg-bg-input border-border-strong text-text-dim hover:text-text",
                    )}
                  >
                    {p.label}
                  </button>
                );
              })}
            </div>
          </div>

          <div className="flex flex-col gap-1.5">
            <Label>Prazo</Label>
            <div className="flex flex-wrap gap-1.5">
              <PrazoChip
                ativa={!usandoCustom && prazoId === null}
                label="Sem prazo"
                onClick={() => {
                  setUsandoCustom(false);
                  setPrazoId(null);
                }}
              />
              {prazos.map((p) => (
                <PrazoChip
                  key={p.id}
                  ativa={!usandoCustom && prazoId === p.id}
                  label={p.nome}
                  onClick={() => {
                    setUsandoCustom(false);
                    setPrazoId(p.id);
                  }}
                />
              ))}
              <PrazoChip
                ativa={usandoCustom}
                label="Data específica…"
                onClick={() => {
                  setUsandoCustom(true);
                  setPrazoId(null);
                }}
              />
            </div>

            {usandoCustom && (
              <div className="grid grid-cols-2 gap-2 mt-2">
                <div className="flex flex-col gap-1">
                  <Label htmlFor="dataCustom">Data</Label>
                  <Input
                    id="dataCustom"
                    type="date"
                    value={dataCustom}
                    onChange={(e) => setDataCustom(e.target.value)}
                  />
                </div>
                <div className="flex flex-col gap-1">
                  <Label htmlFor="horario">Horário final</Label>
                  <Input
                    id="horario"
                    type="time"
                    value={horario}
                    onChange={(e) => setHorario(e.target.value)}
                  />
                </div>
              </div>
            )}
          </div>

          {erro && <p className="text-danger text-xs">{erro}</p>}
        </div>

        <DialogFooter>
          <Button
            variant="secondary"
            onClick={() => onOpenChange(false)}
            disabled={salvando}
          >
            Cancelar
          </Button>
          <Button onClick={enviar} loading={salvando}>
            {editando ? "Salvar" : "Criar tarefa"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

function PrazoChip({
  ativa,
  label,
  onClick,
}: {
  ativa: boolean;
  label: string;
  onClick: () => void;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      className={cn(
        "px-2.5 py-1 rounded text-[13px] border transition-colors",
        ativa
          ? "bg-accent/15 border-accent/40 text-text"
          : "bg-bg-input border-border-strong text-text-dim hover:text-text",
      )}
    >
      {label}
    </button>
  );
}

// front/src/app/features/tarefas/tarefa-form.component.ts
import { CommonModule } from '@angular/common';
import {
  Component,
  EventEmitter,
  Input,
  OnInit,
  Output,
  inject,
  signal,
} from '@angular/core';
import { FormsModule } from '@angular/forms';
import { forkJoin } from 'rxjs';
import { CategoriasService, Categoria } from '../../core/api/categorias.service';
import { Prazo, PrazosService } from '../../core/api/prazos.service';
import {
  CriarTarefaPayload,
  Prioridade,
  Tarefa,
  TarefasService,
} from '../../core/api/tarefas.service';

@Component({
  selector: 'app-tarefa-form',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div
      class="fixed inset-0 bg-black/60 backdrop-blur-sm z-50 grid place-items-center px-4 py-8"
      data-testid="tarefa-form-overlay"
      (click)="fechar()"
    >
      <div
        class="card-elev w-full max-w-[520px] max-h-[90vh] overflow-y-auto"
        (click)="$event.stopPropagation()"
      >
        <div class="flex items-center justify-between border-b border-border px-5 py-3.5">
          <div class="text-sm font-semibold">
            {{ tarefa ? 'Editar tarefa' : 'Nova tarefa' }}
          </div>
          <button
            type="button"
            class="text-text-subtle hover:text-text text-base p-1 leading-none"
            data-testid="tarefa-form-close"
            (click)="fechar()"
          >
            ×
          </button>
        </div>

        <form class="p-5 flex flex-col gap-4" (ngSubmit)="enviar()" #f="ngForm">
          <div class="flex flex-col gap-1.5">
            <label class="field-label" for="nome">Nome</label>
            <input
              id="nome"
              name="nome"
              type="text"
              class="input-base"
              placeholder="O que precisa ser feito"
              data-testid="tarefa-form-nome"
              maxlength="200"
              [(ngModel)]="nome"
              required
            />
          </div>

          <div class="flex flex-col gap-1.5">
            <label class="field-label">Categorias</label>
            <div class="flex flex-wrap gap-1.5" data-testid="tarefa-form-categorias">
              @for (cat of categorias(); track cat.id) {
                <button
                  type="button"
                  class="px-2.5 py-1 rounded text-[13px] border transition-colors"
                  [class]="
                    categoriaIds().includes(cat.id)
                      ? 'bg-accent/15 border-accent/40 text-text'
                      : 'bg-[#16181c] border-border-strong text-text-dim hover:text-text'
                  "
                  [attr.data-testid]="'tarefa-form-cat-' + cat.id"
                  (click)="toggleCategoria(cat.id)"
                >
                  {{ cat.nome }}
                </button>
              } @empty {
                <span class="text-xs text-text-subtle"
                  >Nenhuma categoria cadastrada. Crie em Configurações.</span
                >
              }
            </div>
          </div>

          <div class="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <div class="flex flex-col gap-1.5">
              <label class="field-label" for="prioridade">Prioridade</label>
              <select
                id="prioridade"
                name="prioridade"
                class="input-base"
                data-testid="tarefa-form-prioridade"
                [(ngModel)]="prioridade"
              >
                <option [ngValue]="1">Urgente</option>
                <option [ngValue]="2">Importante</option>
                <option [ngValue]="3">Normal</option>
                <option [ngValue]="4">Baixa</option>
              </select>
            </div>

            <div class="flex flex-col gap-1.5">
              <label class="field-label" for="prazo">Prazo</label>
              <select
                id="prazo"
                name="prazo"
                class="input-base"
                data-testid="tarefa-form-prazo"
                [(ngModel)]="prazoEscolha"
                (ngModelChange)="onPrazoChange($event)"
              >
                <option [ngValue]="null">Sem prazo</option>
                @for (p of prazos(); track p.id) {
                  <option [ngValue]="p.id">{{ p.nome }}</option>
                }
                <option ngValue="custom">Data específica…</option>
              </select>
            </div>
          </div>

          @if (prazoEscolha === 'custom') {
            <div class="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <div class="flex flex-col gap-1.5">
                <label class="field-label" for="dataCustom">Data</label>
                <input
                  id="dataCustom"
                  name="dataCustom"
                  type="date"
                  class="input-base"
                  data-testid="tarefa-form-data-custom"
                  [(ngModel)]="dataCustom"
                />
              </div>
              <div class="flex flex-col gap-1.5">
                <label class="field-label" for="horario">Horário final</label>
                <input
                  id="horario"
                  name="horario"
                  type="time"
                  class="input-base"
                  data-testid="tarefa-form-horario"
                  [(ngModel)]="horario"
                />
              </div>
            </div>
          }

          @if (erro()) {
            <p class="text-danger text-xs" data-testid="tarefa-form-erro">{{ erro() }}</p>
          }

          <div class="flex justify-end gap-2 pt-2">
            <button
              type="button"
              class="btn-secondary"
              data-testid="tarefa-form-cancelar"
              (click)="fechar()"
            >
              Cancelar
            </button>
            <button
              type="submit"
              class="btn-primary"
              data-testid="tarefa-form-salvar"
              [disabled]="salvando() || f.invalid"
            >
              {{ salvando() ? 'Salvando...' : tarefa ? 'Salvar' : 'Criar tarefa' }}
            </button>
          </div>
        </form>
      </div>
    </div>
  `,
})
export class TarefaFormComponent implements OnInit {
  private readonly categoriasApi = inject(CategoriasService);
  private readonly prazosApi = inject(PrazosService);
  private readonly tarefasApi = inject(TarefasService);

  @Input() tarefa: Tarefa | null = null;
  @Input() nomeInicial = '';
  @Output() salvo = new EventEmitter<Tarefa>();
  @Output() cancelado = new EventEmitter<void>();

  readonly categorias = signal<Categoria[]>([]);
  readonly prazos = signal<Prazo[]>([]);
  readonly categoriaIds = signal<string[]>([]);
  readonly salvando = signal(false);
  readonly erro = signal<string | null>(null);

  nome = '';
  prioridade: Prioridade = 3;
  prazoEscolha: string | null = null;
  dataCustom = '';
  horario = '23:59';

  ngOnInit(): void {
    forkJoin({
      cats: this.categoriasApi.listar(),
      prz: this.prazosApi.listar(),
    }).subscribe(({ cats, prz }) => {
      this.categorias.set(cats);
      this.prazos.set(prz);
    });

    if (this.tarefa) {
      this.nome = this.tarefa.nome;
      this.prioridade = this.tarefa.prioridade;
      this.categoriaIds.set(this.tarefa.categorias.map((c) => c.id));
      if (this.tarefa.prazoId) {
        this.prazoEscolha = this.tarefa.prazoId;
      } else if (this.tarefa.dataPrazo) {
        this.prazoEscolha = 'custom';
        this.dataCustom = this.tarefa.dataPrazo.substring(0, 10);
      }
      if (this.tarefa.horarioFinal) {
        this.horario = this.tarefa.horarioFinal.substring(0, 5);
      }
    } else {
      this.nome = this.nomeInicial;
    }
  }

  toggleCategoria(id: string): void {
    this.categoriaIds.update((ids) =>
      ids.includes(id) ? ids.filter((i) => i !== id) : [...ids, id],
    );
  }

  onPrazoChange(_: string | null): void {
    if (this.prazoEscolha !== 'custom') {
      this.dataCustom = '';
    }
  }

  fechar(): void {
    if (this.salvando()) return;
    this.cancelado.emit();
  }

  enviar(): void {
    if (this.salvando()) return;

    const payload: CriarTarefaPayload = {
      nome: this.nome,
      prioridade: this.prioridade,
      categoriaIds: this.categoriaIds(),
      prazoId: null,
      dataPrazoCustom: null,
      horarioFinal: null,
    };

    if (this.prazoEscolha === 'custom') {
      if (!this.dataCustom) {
        this.erro.set('Informa a data ou escolhe outro prazo.');
        return;
      }
      payload.dataPrazoCustom = new Date(this.dataCustom + 'T00:00:00').toISOString();
      if (this.horario) {
        const [h, m] = this.horario.split(':');
        payload.horarioFinal = `${h.padStart(2, '0')}:${m.padStart(2, '0')}:00`;
      }
    } else if (this.prazoEscolha) {
      payload.prazoId = this.prazoEscolha;
    }

    this.salvando.set(true);
    this.erro.set(null);

    const req$ = this.tarefa
      ? this.tarefasApi.atualizar(this.tarefa.id, payload)
      : this.tarefasApi.criar(payload);

    req$.subscribe({
      next: (t) => {
        this.salvando.set(false);
        this.salvo.emit(t);
      },
      error: (err) => {
        this.salvando.set(false);
        this.erro.set(err?.error?.mensagem ?? 'Não consegui salvar. Tenta de novo.');
      },
    });
  }
}
