// front/src/app/features/captura/captura.component.ts
import { Component, HostListener, inject, signal } from '@angular/core';
import { Router } from '@angular/router';
import { TokenStorage } from '../../core/auth/token.storage';
import { TarefaFormComponent } from '../tarefas/tarefa-form.component';

type Modo = 'manual' | 'jarvis' | null;

@Component({
  selector: 'app-captura',
  standalone: true,
  imports: [TarefaFormComponent],
  template: `
    <header class="flex items-center px-4 md:px-8 py-3.5 border-b border-border gap-4">
      <div class="flex items-center gap-2 text-[13px] text-text-dim">
        <i class="fa-solid fa-bolt text-accent text-[11px]"></i>
        <strong class="text-text font-medium">Captura Rápida</strong>
      </div>
    </header>

    <div
      class="flex-1 grid place-items-center px-4 md:px-8 py-8 md:py-12 bg-bg"
      style="background-image: radial-gradient(ellipse 60% 30% at 50% 0%, rgba(94, 106, 210, 0.08), transparent);"
      data-testid="captura-page"
    >
      <div class="w-full max-w-[720px] flex flex-col gap-8 md:gap-10 items-center">
        <div class="text-center flex flex-col gap-2.5">
          <h1 class="text-2xl md:text-[28px] font-semibold tracking-tight leading-tight" data-testid="jarvis-greeting">
            {{ saudacao() }}{{ nomeUsuario() ? ', ' + nomeUsuario() : '' }}
          </h1>
          <div class="text-lg font-medium text-text-dim tracking-tight" data-testid="jarvis-prompt">
            O que você precisa anotar?
          </div>
          <p class="text-text-dim max-w-[440px] mx-auto leading-relaxed">
            Escolha como quer criar a tarefa. Manual pra quando você já sabe tudo, Jarvis pra
            quando quer que eu organize pra você.
          </p>
        </div>

        <div class="grid grid-cols-1 sm:grid-cols-2 gap-4 w-full" data-testid="mode-picker">
          <button
            type="button"
            class="bg-bg-elev border border-border rounded-lg p-6 cursor-pointer text-left flex flex-col gap-3.5 hover:border-border-strong hover:bg-[#16181c] transition-colors group"
            data-testid="mode-manual-btn"
            (click)="abrirManual()"
          >
            <div class="flex items-center justify-between gap-3">
              <div
                class="w-9 h-9 rounded-lg bg-[#16181c] border border-border-strong grid place-items-center text-text-dim text-[15px]"
              >
                <i class="fa-solid fa-pen-to-square"></i>
              </div>
            </div>
            <div class="text-base font-semibold tracking-tight text-text-dim">Manual</div>
            <div class="text-[13px] text-text-dim leading-relaxed">
              Você preenche os campos na mão: nome, categoria, prazo e prioridade. Rápido e sem
              surpresas.
            </div>
            <div
              class="flex items-center justify-between mt-1.5 pt-3.5 border-t border-border"
            >
              <div class="text-[13px] font-medium text-text group-hover:text-accent flex items-center gap-1.5">
                Criar tarefa
                <i class="fa-solid fa-arrow-right text-[11px]"></i>
              </div>
              <span class="kbd-pill">M</span>
            </div>
          </button>

          <button
            type="button"
            class="relative overflow-hidden bg-bg-elev border border-border rounded-lg p-6 cursor-pointer text-left flex flex-col gap-3.5 hover:border-accent hover:bg-[#16181c] transition-colors group"
            data-testid="mode-jarvis-btn"
            (click)="avisoJarvis()"
            [style.background-image]="'radial-gradient(ellipse 80% 60% at 100% 0%, rgba(94, 106, 210, 0.08), transparent)'"
          >
            <div class="flex items-center justify-between gap-3 relative">
              <div
                class="w-9 h-9 rounded-lg bg-accent/15 border border-accent/30 grid place-items-center text-accent text-[15px]"
              >
                <i class="fa-solid fa-wand-magic-sparkles"></i>
              </div>
              <span
                class="text-[10px] font-semibold px-1.5 py-0.5 rounded bg-accent/15 text-accent tracking-wider"
                >EM BREVE</span
              >
            </div>
            <div class="text-base font-semibold tracking-tight text-accent">Jarvis</div>
            <div class="text-[13px] text-text-dim leading-relaxed">
              Me conta em texto livre o que você precisa fazer. Eu categorizo, defino prazo e te
              mando pra revisão.
            </div>
            <div
              class="flex items-center justify-between mt-1.5 pt-3.5 border-t border-border"
            >
              <div class="text-[13px] font-medium text-text-dim flex items-center gap-1.5">
                Disponível em breve
              </div>
              <span class="kbd-pill">J</span>
            </div>
          </button>
        </div>

        <div class="flex items-center gap-2.5 text-text-subtle text-xs" data-testid="keyboard-hint">
          <i class="fa-solid fa-keyboard"></i>
          <span>Use <span class="kbd-pill">M</span> pra abrir o modo manual.</span>
        </div>

        @if (avisoIa()) {
          <div
            class="fixed bottom-6 right-6 bg-bg-elev border border-border rounded px-4 py-3 text-[13px] text-text-dim shadow-lg max-w-xs"
            data-testid="aviso-ia"
          >
            Modo Jarvis (IA) ainda não está disponível. Por enquanto, usa o modo Manual.
          </div>
        }
      </div>
    </div>

    @if (modo() === 'manual') {
      <app-tarefa-form
        (salvo)="aposSalvar()"
        (cancelado)="modo.set(null)"
      ></app-tarefa-form>
    }
  `,
  styles: [
    `
      .kbd-pill {
        display: inline-flex;
        align-items: center;
        justify-content: center;
        min-width: 20px;
        height: 20px;
        padding: 0 5px;
        border: 1px solid #2a2b2f;
        border-radius: 4px;
        background: #16181c;
        font-family: 'SF Mono', ui-monospace, monospace;
        font-size: 11px;
        color: #8a8f98;
      }
    `,
  ],
})
export class CapturaComponent {
  private readonly storage = inject(TokenStorage);
  private readonly router = inject(Router);

  readonly modo = signal<Modo>(null);
  readonly avisoIa = signal(false);
  readonly nomeUsuario = signal(this.storage.usuario()?.nome ?? '');

  saudacao(): string {
    const h = new Date().getHours();
    if (h < 6) return 'Boa madrugada';
    if (h < 12) return 'Bom dia';
    if (h < 18) return 'Boa tarde';
    return 'Boa noite';
  }

  abrirManual(): void {
    this.modo.set('manual');
  }

  avisoJarvis(): void {
    this.avisoIa.set(true);
    setTimeout(() => this.avisoIa.set(false), 3500);
  }

  aposSalvar(): void {
    this.modo.set(null);
  }

  @HostListener('window:keydown', ['$event'])
  onKey(ev: KeyboardEvent): void {
    if (this.modo() !== null) return;
    const tag = (ev.target as HTMLElement)?.tagName;
    if (tag === 'INPUT' || tag === 'TEXTAREA' || tag === 'SELECT') return;

    if (ev.key === 'm' || ev.key === 'M') {
      ev.preventDefault();
      this.abrirManual();
    } else if (ev.key === 'j' || ev.key === 'J') {
      ev.preventDefault();
      this.avisoJarvis();
    }
  }
}

// front2/app/(app)/captura.tsx
import { Ionicons } from "@expo/vector-icons";
import { useState } from "react";
import { Pressable, ScrollView, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { toast } from "sonner-native";

import { Header } from "@/components/Header";
import { TarefaForm } from "@/components/TarefaForm";
import { useAuthStore } from "@/stores/auth";

function saudacao(): string {
  const h = new Date().getHours();
  if (h < 5) return "Boa madrugada";
  if (h < 12) return "Bom dia";
  if (h < 18) return "Boa tarde";
  return "Boa noite";
}

export default function Captura() {
  const usuario = useAuthStore((s) => s.usuario);
  const [formAberto, setFormAberto] = useState(false);

  const primeiroNome = usuario?.nome.split(" ")[0] ?? "";

  return (
    <SafeAreaView className="flex-1 bg-bg" edges={["top"]}>
      <Header icon="flash" title="Captura Rápida" />

      <ScrollView
        contentContainerStyle={{
          flexGrow: 1,
          paddingHorizontal: 24,
          paddingVertical: 32,
          gap: 32,
          alignItems: "center",
        }}
      >
        <View className="items-center gap-2.5 max-w-[440px]">
          <Text
            className="text-[24px] text-text font-semibold tracking-tight text-center"
            testID="jarvis-greeting"
          >
            {saudacao()}
            {primeiroNome ? `, ${primeiroNome}` : ""}
          </Text>
          <Text className="text-text-dim text-base font-medium tracking-tight">
            O que você precisa anotar?
          </Text>
          <Text className="text-text-dim text-[13px] text-center leading-relaxed">
            Escolha como quer criar a tarefa. Manual pra quando você já sabe
            tudo, Jarvis pra quando quer que eu organize pra você.
          </Text>
        </View>

        <View className="w-full gap-3 max-w-[440px]">
          <ModoCard
            icon="create-outline"
            titulo="Manual"
            descricao="Você preenche os campos: nome, categoria, prazo e prioridade. Rápido e sem surpresas."
            onPress={() => setFormAberto(true)}
            testID="mode-manual"
          />
          <ModoCard
            icon="sparkles-outline"
            titulo="Jarvis"
            descricao="Escreve livre e eu organizo: categorizo, defino prazo, prioridade. Você só revisa."
            onPress={() =>
              toast("Modo Jarvis chega em breve. Por ora, usa o Manual.")
            }
            testID="mode-jarvis"
            disabled
          />
        </View>
      </ScrollView>

      <TarefaForm visible={formAberto} onClose={() => setFormAberto(false)} />
    </SafeAreaView>
  );
}

function ModoCard({
  icon,
  titulo,
  descricao,
  onPress,
  testID,
  disabled,
}: {
  icon: keyof typeof Ionicons.glyphMap;
  titulo: string;
  descricao: string;
  onPress: () => void;
  testID?: string;
  disabled?: boolean;
}) {
  return (
    <Pressable
      onPress={onPress}
      testID={testID}
      className={`bg-bg-elev border border-border rounded-lg p-5 gap-3 active:border-border-strong ${
        disabled ? "opacity-60" : ""
      }`}
    >
      <View className="flex-row items-center justify-between">
        <View className="w-9 h-9 rounded-md bg-bg-input border border-border-strong items-center justify-center">
          <Ionicons name={icon} size={18} color="#8a8f98" />
        </View>
        {disabled && (
          <View className="px-2 py-0.5 rounded-full bg-bg-input border border-border">
            <Text className="text-text-subtle text-[10px] tracking-wider">
              EM BREVE
            </Text>
          </View>
        )}
      </View>
      <Text className="text-base font-semibold tracking-tight text-text">
        {titulo}
      </Text>
      <Text className="text-text-dim text-[13px] leading-relaxed">
        {descricao}
      </Text>
    </Pressable>
  );
}
