// front/src/app/shared/password-requirements.component.ts
import { Component, Input, computed, inject, signal } from '@angular/core';
import { LocaleService } from '../core/locale/locale.service';

export interface RequisitosSenha {
  tamanho: boolean;
  maiuscula: boolean;
  especial: boolean;
}

export function avaliarSenha(senha: string): RequisitosSenha {
  return {
    tamanho: senha.length >= 8,
    maiuscula: /[A-Z]/.test(senha),
    especial: /[^A-Za-z0-9]/.test(senha),
  };
}

export function senhaAtendeRequisitos(senha: string): boolean {
  const r = avaliarSenha(senha);
  return r.tamanho && r.maiuscula && r.especial;
}

@Component({
  selector: 'app-password-requirements',
  standalone: true,
  template: `
    <ul
      class="flex flex-col gap-1 text-[11px]"
      [attr.data-testid]="testid"
      [attr.aria-label]="locale.t('password_req.aria')"
    >
      <li
        class="flex items-center gap-2 transition-colors"
        [class.text-emerald-400]="reqs().tamanho"
        [class.text-text-subtle]="!reqs().tamanho"
        [attr.data-testid]="testid + '-tamanho'"
        [attr.data-met]="reqs().tamanho"
      >
        @if (reqs().tamanho) {
          <i class="fa-solid fa-check w-3 text-center"></i>
        } @else {
          <i class="fa-solid fa-circle text-[5px] w-3 text-center"></i>
        }
        {{ locale.t('password_req.length') }}
      </li>
      <li
        class="flex items-center gap-2 transition-colors"
        [class.text-emerald-400]="reqs().maiuscula"
        [class.text-text-subtle]="!reqs().maiuscula"
        [attr.data-testid]="testid + '-maiuscula'"
        [attr.data-met]="reqs().maiuscula"
      >
        @if (reqs().maiuscula) {
          <i class="fa-solid fa-check w-3 text-center"></i>
        } @else {
          <i class="fa-solid fa-circle text-[5px] w-3 text-center"></i>
        }
        {{ locale.t('password_req.uppercase') }}
      </li>
      <li
        class="flex items-center gap-2 transition-colors"
        [class.text-emerald-400]="reqs().especial"
        [class.text-text-subtle]="!reqs().especial"
        [attr.data-testid]="testid + '-especial'"
        [attr.data-met]="reqs().especial"
      >
        @if (reqs().especial) {
          <i class="fa-solid fa-check w-3 text-center"></i>
        } @else {
          <i class="fa-solid fa-circle text-[5px] w-3 text-center"></i>
        }
        {{ locale.t('password_req.special') }}
      </li>
    </ul>
  `,
})
export class PasswordRequirementsComponent {
  readonly locale = inject(LocaleService);
  private readonly senhaSignal = signal('');

  @Input() set senha(v: string) {
    this.senhaSignal.set(v ?? '');
  }
  @Input() testid = 'password-requirements';

  readonly reqs = computed(() => avaliarSenha(this.senhaSignal()));
}

// landing/components/auth/password-requirements.tsx
"use client";

import { useTranslations } from "next-intl";

import { avaliarSenha } from "@/lib/auth/password";

export function PasswordRequirements({ senha }: { senha: string }) {
  const t = useTranslations("Auth.passwordReq");
  const reqs = avaliarSenha(senha);

  const items: { key: keyof typeof reqs; label: string }[] = [
    { key: "tamanho", label: t("length") },
    { key: "maiuscula", label: t("uppercase") },
    { key: "especial", label: t("special") },
  ];

  return (
    <ul className="flex flex-col gap-1 text-[11px]" aria-label={t("aria")}>
      {items.map((item) => {
        const ok = reqs[item.key];
        return (
          <li
            key={item.key}
            className={`flex items-center gap-2 transition-colors ${ok ? "text-success" : "text-faint"}`}
            data-met={ok}
          >
            <span className="w-3 inline-flex justify-center">
              {ok ? (
                <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" aria-hidden>
                  <path d="M5 12.5l4.5 4.5L19 7" />
                </svg>
              ) : (
                <span className="w-1 h-1 rounded-pill bg-current opacity-60" aria-hidden />
              )}
            </span>
            <span>{item.label}</span>
          </li>
        );
      })}
    </ul>
  );
}
